//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyBridgeBeamNGExporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PolyBridgeBeamNGExporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;asset&gt;
        ///    &lt;contributor&gt;
        ///      &lt;author&gt;Bridge Maker&lt;/author&gt;
        ///      &lt;authoring_tool&gt;PolyBridgeBeamNGExporter&lt;/authoring_tool&gt;
        ///    &lt;/contributor&gt;
        ///    &lt;unit name=&quot;meter&quot; meter=&quot;1&quot;/&gt;
        ///    &lt;up_axis&gt;Y_UP&lt;/up_axis&gt;
        ///  &lt;/asset&gt;.
        /// </summary>
        internal static string ColladaHeader {
            get {
                return ResourceManager.GetString("ColladaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;model_pb_wood&quot; : {
        ///    &quot;name&quot; : &quot;model_pb_wood&quot;,
        ///    &quot;mapTo&quot; : &quot;pb_wood&quot;,
        ///    &quot;class&quot; : &quot;material&quot;,
        ///    &quot;persistentId&quot; : &quot;4fcef887-e70e-48d2-89ab-2c3070303744&quot;,
        ///    &quot;Stages&quot; : [
        ///      {
        ///        &quot;diffuseColor&quot; : [ 0.63921568627450980392156862745098, 0.41568627450980392156862745098039, 0.0, 1 ]
        ///      },
        ///      {},
        ///      {},
        ///      {}
        ///    ],
        ///    &quot;translucentBlendOp&quot; : &quot;None&quot;
        ///  },
        ///  &quot;model_pb_cable&quot; : {
        ///    &quot;name&quot; : &quot;model_pb_cable&quot;,
        ///    &quot;mapTo&quot; : &quot;pb_cable&quot;,
        ///    &quot;class&quot; : &quot;material&quot;,
        ///    &quot;persistentId&quot; : &quot;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaterialsFile {
            get {
                return ResourceManager.GetString("MaterialsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pb_thumbnail {
            get {
                object obj = ResourceManager.GetObject("pb_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
